// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://beabtoyyzgeqxpodpuji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlYWJ0b3l5emdlcXhwb2RwdWppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMjIwNzcsImV4cCI6MjA1OTY5ODA3N30.7jMhu1RQ8Og_IW5a7LJBZrYmTl04ya1_lRRmKPoZ-JY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);